version: "3.7"
services:
  web:
    image: 'gitlab/gitlab-ce:rc'
    restart: always
    container_name: 'gitlab'
    hostname: '192.168.99.100'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.99.100'
        letsencrypt['enable'] = false
    ports:
      - '80:80'
      - '2222:22'
      